name: Publish Site

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          PERSONAL_AWS_ACCESS_KEY: ${{ secrets.PERSONAL_AWS_ACCESS_KEY }}
          PERSONAL_AWS_SECRET_KEY: ${{ secrets.PERSONAL_AWS_SECRET_KEY }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
